#!/usr/bin/env python3
from pathlib import Path
import sys, tempfile, py_compile

if len(sys.argv) != 2:
    raise SystemExit("uso: patch-archive-gc.py SOURCE_ROOT")

root = Path(sys.argv[1])
appdir = root / "app"
archive_py = appdir / "archive_import.py"
tpl = appdir / "templates" / "api_manager.html"

if not archive_py.exists():
    raise SystemExit("Archive GC: app/archive_import.py ausente")

src = archive_py.read_text(encoding="utf-8")
if "RM_ARCHIVE_GC_V1" not in src:
    addon = r'''

# RM_ARCHIVE_GC_V1
# Garbage collector seguro para /cache/archive-import.
# - nunca apaga job ativo/queued/waiting_password;
# - preserva interrupted/error recentes para permitir Continuar;
# - remove staging de jobs inexistentes/terminal;
# - remove staging de interrupted/error apenas depois da retenção configurada;
# - roda no startup e periodicamente, sem exigir intervenção manual.
import os as _rmgc_os
import shutil as _rmgc_shutil
import threading as _rmgc_threading
import time as _rmgc_time
from pathlib import Path as _RmgcPath


_RMGC_RETENTION_HOURS = max(
    1, min(168, int(_rmgc_os.environ.get('RM_ARCHIVE_ORPHAN_RETENTION_HOURS', '24') or 24))
)
_RMGC_INTERVAL_SECONDS = max(
    300, min(86400, int(_rmgc_os.environ.get('RM_ARCHIVE_GC_INTERVAL_SECONDS', '900') or 900))
)
_RMGC_LOCK = _rmgc_threading.RLock()
_RMGC_LAST = {
    'last_run': 0,
    'freed_bytes': 0,
    'removed_jobs': 0,
    'kept_recent_bytes': 0,
    'orphan_bytes': 0,
    'reason': '',
}

_RMGC_ORIG_MANAGER_STATUS = globals().get('archive_manager_status')
_RMGC_ORIG_MANAGER_COMMAND = globals().get('archive_manager_command')
_RMGC_ORIG_CAN_START = globals().get('_rmqm_can_start')


def _rmgc_dir_bytes(path):
    total = 0
    try:
        for p in _RmgcPath(path).rglob('*'):
            if p.is_file():
                try:
                    total += int(p.stat().st_size)
                except Exception:
                    pass
    except Exception:
        pass
    return total


def _rmgc_parse_epoch(value):
    if not value:
        return 0.0
    s = str(value).strip()
    if not s:
        return 0.0
    try:
        # Handles ISO strings generated by the Manager, including Z/+00:00.
        from datetime import datetime
        return datetime.fromisoformat(s.replace('Z', '+00:00')).timestamp()
    except Exception:
        return 0.0


def _rmgc_job_age_seconds(job):
    now = _rmgc_time.time()
    for key in ('updated_at', 'finished_at', 'created_at'):
        ts = _rmgc_parse_epoch((job or {}).get(key))
        if ts > 0:
            return max(0.0, now - ts)
    return 0.0


def _rmgc_job_map():
    rows = []
    try:
        # Prefer the raw manager list if present to avoid UI wrappers.
        fn = globals().get('_RMQM_ORIG_LIST_JOBS') or globals().get('_ARCHIVE_ORIG_LIST_JOBS') or list_jobs
        rows = fn(1000) or []
    except Exception:
        try:
            rows = list_jobs(1000) or []
        except Exception:
            rows = []
    out = {}
    for row in rows:
        if not isinstance(row, dict):
            continue
        jid = str(row.get('id') or row.get('job_id') or '').strip()
        if jid:
            out[jid] = row
    return out


def _rmgc_worker_alive(job_id):
    fn = globals().get('_rmqm_worker_alive') or globals().get('_archive_worker_alive')
    if callable(fn):
        try:
            return bool(fn(job_id))
        except Exception:
            return False
    try:
        with _JOB_LOCK:
            th = _JOB_THREADS.get(str(job_id))
            return bool(th and th.is_alive())
    except Exception:
        return False


def archive_gc_status():
    with _RMGC_LOCK:
        data = dict(_RMGC_LAST)
    data['retention_hours'] = _RMGC_RETENTION_HOURS
    data['interval_seconds'] = _RMGC_INTERVAL_SECONDS
    return data


def archive_gc_run(reason='manual', include_old=True):
    now = _rmgc_time.time()
    retention = _RMGC_RETENTION_HOURS * 3600
    jobs = _rmgc_job_map()

    active_states = {
        'running', 'queued', 'pending', 'waiting', 'waiting_password',
        'password', 'needs_password', 'starting', 'downloading',
        'download', 'download_retry', 'auto_retry', 'extracting',
        'extracting_staging', 'streaming', 'uploading', 'cleanup',
        'cleaning', 'canceling', 'waiting_space',
    }
    terminal_states = {
        'done', 'completed', 'complete', 'success',
        'canceled', 'cancelled', 'deleted',
    }
    resumable_states = {'interrupted', 'error', 'failed'}

    freed = 0
    removed = 0
    kept_recent = 0
    orphan_bytes = 0

    root = _RmgcPath(STAGING_ROOT)
    try:
        stages = [p for p in root.glob('job-*') if p.is_dir()]
    except Exception:
        stages = []

    for stage in stages:
        jid = stage.name[4:] if stage.name.startswith('job-') else ''
        size = _rmgc_dir_bytes(stage)
        job = jobs.get(jid)

        remove = False
        if not jid or job is None:
            # No DB row owns this staging anymore: always garbage.
            remove = True
            orphan_bytes += size
        else:
            status = str(job.get('status') or '').lower()

            # A live worker always wins over stale DB state.
            if _rmgc_worker_alive(jid):
                continue

            if status in active_states:
                # queued/waiting/password are intentionally preserved.
                continue

            if status in terminal_states:
                remove = True

            elif status in resumable_states:
                age = _rmgc_job_age_seconds(job)
                if include_old and age >= retention:
                    remove = True
                else:
                    kept_recent += size

            else:
                # Unknown states are preserved unless the DB row is very old.
                age = _rmgc_job_age_seconds(job)
                if include_old and age >= retention * 2:
                    remove = True
                else:
                    kept_recent += size

        if remove:
            try:
                _rmgc_shutil.rmtree(stage, ignore_errors=False)
                freed += size
                removed += 1
            except Exception:
                pass

    with _RMGC_LOCK:
        _RMGC_LAST.update({
            'last_run': int(now),
            'freed_bytes': int(freed),
            'removed_jobs': int(removed),
            'kept_recent_bytes': int(kept_recent),
            'orphan_bytes': int(orphan_bytes),
            'reason': str(reason or ''),
        })

    return {
        'ok': True,
        **archive_gc_status(),
    }


def _rmgc_disk_below_minimum():
    cfg = {}
    state = globals().get('_RMQM_STATE')
    if isinstance(state, dict):
        cfg = state.get('settings') or {}
    try:
        min_free = int(cfg.get('min_free_gb') or 10) * 1024**3
    except Exception:
        min_free = 10 * 1024**3
    try:
        free = int(_rmgc_shutil.disk_usage(STAGING_ROOT).free)
    except Exception:
        free = 0
    return bool(free and free < min_free)


if callable(_RMGC_ORIG_CAN_START):
    def _rmqm_can_start(job):
        # Cheap policy: before refusing a new job for low disk, first remove
        # definitely safe garbage. Recent interrupted/error stages are kept.
        if _rmgc_disk_below_minimum():
            try:
                archive_gc_run(reason='low_disk', include_old=False)
            except Exception:
                pass
        return _RMGC_ORIG_CAN_START(job)


if callable(_RMGC_ORIG_MANAGER_STATUS):
    def archive_manager_status():
        data = _RMGC_ORIG_MANAGER_STATUS()
        if isinstance(data, dict):
            data = dict(data)
            data['gc'] = archive_gc_status()
        return data


if callable(_RMGC_ORIG_MANAGER_COMMAND):
    def archive_manager_command(payload=None):
        payload = payload if isinstance(payload, dict) else {}
        action = str(payload.get('action') or '').strip().lower()

        if action == 'gc_now':
            return {
                'ok': True,
                'gc': archive_gc_run(reason='manual', include_old=False),
                **archive_manager_status(),
            }
        if action == 'gc_old':
            return {
                'ok': True,
                'gc': archive_gc_run(reason='manual_old', include_old=True),
                **archive_manager_status(),
            }
        return _RMGC_ORIG_MANAGER_COMMAND(payload)


def _rmgc_loop():
    # Startup cleanup only removes definitely safe garbage + old resumables.
    try:
        archive_gc_run(reason='startup', include_old=True)
    except Exception:
        pass
    while True:
        _rmgc_time.sleep(_RMGC_INTERVAL_SECONDS)
        try:
            archive_gc_run(reason='periodic', include_old=True)
        except Exception:
            pass


_rmgc_threading.Thread(
    target=_rmgc_loop,
    name='archive-staging-gc',
    daemon=True,
).start()
'''
    archive_py.write_text(src + addon, encoding="utf-8")
    with tempfile.NamedTemporaryFile(suffix=".pyc") as f:
        py_compile.compile(str(archive_py), doraise=True, cfile=f.name)

if tpl.exists():
    page = tpl.read_text(encoding="utf-8")
    if "RM_ARCHIVE_GC_UI_V1" not in page:
        ui = r'''
<!-- RM_ARCHIVE_GC_UI_V1 -->
<script>
(() => {
  const fmtBytes=n=>{
    n=Number(n||0); if(!n)return '0 B';
    const u=['B','KB','MB','GB','TB']; let i=0;
    while(n>=1024&&i<u.length-1){n/=1024;i++}
    return n.toFixed(i>=3?1:0)+' '+u[i];
  };

  async function api(body){
    const r=await fetch('/api/v1/archive/manager',{
      method:'POST',credentials:'same-origin',cache:'no-store',
      headers:{'Content-Type':'application/json'},
      body:JSON.stringify(body)
    });
    const d=await r.json().catch(()=>({}));
    if(!r.ok||d.ok===false)throw new Error(d.error||('HTTP '+r.status));
    return d;
  }

  function ensure(){
    const root=document.getElementById('rmArchiveManagerV2'); if(!root)return;
    const controls=root.querySelector('.rmqm-manager-controls')||root.querySelector('.rm-arc-head');
    if(!controls||root.querySelector('#rmgcSafeBtn'))return;

    const safe=document.createElement('button');
    safe.id='rmgcSafeBtn';
    safe.type='button';
    safe.textContent='Limpar temporários órfãos';
    safe.title='Remove staging sem job no banco e resíduos de tarefas concluídas/canceladas.';
    safe.onclick=async()=>{
      if(!confirm('Limpar apenas temporários seguros/órfãos? Jobs ativos e interrompidos recentes serão preservados.'))return;
      try{
        const d=await api({action:'gc_now'});
        const g=d.gc||{};
        alert('Limpeza concluída: '+fmtBytes(g.freed_bytes)+' liberados em '+Number(g.removed_jobs||0)+' staging(s).');
        document.getElementById('rmArcRefreshV2')?.click();
      }catch(e){alert(e.message)}
    };
    controls.appendChild(safe);

    const old=document.createElement('button');
    old.id='rmgcOldBtn';
    old.type='button';
    old.textContent='Limpar antigos >24h';
    old.title='Também remove staging de jobs interrupted/error com mais de 24h.';
    old.onclick=async()=>{
      if(!confirm('Remover também temporários de tarefas interrompidas/com erro com mais de 24h? Depois elas precisarão baixar novamente.'))return;
      try{
        const d=await api({action:'gc_old'});
        const g=d.gc||{};
        alert('Limpeza concluída: '+fmtBytes(g.freed_bytes)+' liberados em '+Number(g.removed_jobs||0)+' staging(s).');
        document.getElementById('rmArcRefreshV2')?.click();
      }catch(e){alert(e.message)}
    };
    controls.appendChild(old);
  }

  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ensure,{once:true});
  else ensure();
  document.addEventListener('rm-archive-jobs',ensure);
})();
</script>
'''
        end = page.rfind("{% endblock %}")
        if end >= 0:
            page = page[:end] + ui + "\n" + page[end:]
        else:
            page += "\n" + ui
        tpl.write_text(page, encoding="utf-8")

print("Archive GC OK: limpeza segura de staging + retenção 24h + proteção de jobs ativos")
